version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: project_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: services/app/Dockerfile
    container_name: project_app
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["php-fpm"]
    volumes:
      - ./:/var/www/html:delegated
      - ./public/assets:/var/www/html/public/assets:delegated
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ["/home/mauri/ciclismo-monolito/database/database.sqlite"]
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: project_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/assets:/var/www/html/public/assets:ro
    depends_on:
      - app
      - db:
        condition: service_healthy


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: project_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

  redis:
    image: redis:6-alpine
    container_name: project_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
