apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-namespace
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_LOG_CHANNEL: "stack"
  DB_HOST: "mysql"
  DB_DATABASE: "laravel"
  DB_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app-namespace
type: Opaque
data:
  # base64 encoded values
  DB_USERNAME: bGFyYXZlbA==        # laravel
  DB_PASSWORD: c2VjcmV0            # secret
  APP_KEY: BASE64_ENCODED_APP_KEY  # reemplaza por php artisan key:generate --show y base64
